### ISSUE TITLE
The Tokenly components are missing

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat-org#623]
I noticed that dev.fermat.org and dev.bitdubai.com they are not showing the **Tokenly** (TKY) components, this components was properly loaded I used to create workflows in my previous bounty, where are this components right now?

Thanks in advance.

**Comment by Miguelcldn** [comment]
Since several days, at the server were some scripts that updated the BD from the old manifest.xml file, when some members from the server side left, they left those scripts there, where someone else outside our team had access and ran them, cleaning up the BD and adding the elements present in the manifest again, so data lost was made and the former members didn't configure the server to make regular backups, so we couldn't recover the lost data. Now those scripts are stashed and we are working to create backups for the DB so that lost is not repeated, we are sorry for the hard work being lost.

**Comment by darkestpriest** [comment]
@Miguelcldn why you close this issue? My data is still missing.
